name: Create report based on issue labels
on:
  workflow_dispatch:

jobs:
  reportOnIssuesByLabel:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workspace
        run: echo "$GITHUB_WORKSPACE"
      - uses: octokit/request-action@v2.x
        id: get_issues_by_label
        with:
          route: GET /repos/{owner}/{repo}/issues?labels={label}
          label: 1 point
          owner: aaugustine
          repo: recipe-box
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo issues by label: ${{ fromJson(steps.get_issues_by_label.outputs.data) }}"
      - uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs')
            const path = process.env.GITHUB_WORKSPACE+"/data.csv"
            const issues = ${{ steps.get_issues_by_label.outputs.data }}
            
            for (const issue of issues) {
              const line;
              line = issue.title +','+ issue.number.toString()
              fs.writeFile(path,line,{flag: 'a'}, err=> {})
            }
      - name: Check for file
        run: "ls -la  $GITHUB_WORKSPACE"
      - name: Export CSV report
        uses: actions/upload-artifact@v2
        with:
          name: issue-report
          path: ${{github.workspace}}/data.csv
