name: Create report based on issue labels
on:
  workflow_dispatch:

jobs:
  reportOnIssuesByLabel:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workspace
        run: echo "$GITHUB_WORKSPACE"
      - uses: octokit/request-action@v2.x
        id: get_issues_by_label
        with:
          route: GET /repos/{owner}/{repo}/issues?labels={label}
          label: 1 point
          owner: aaugustine
          repo: recipe-box
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo issues by label: ${{ fromJson(steps.get_issues_by_label.outputs.data) }}"
      - uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs')
            const path = ${{GITHUB_WORKSPACE}}/data.csv
            const issues = ${{ steps.get_issues_by_label.outputs.data }}
            
            for (const issue of issues) {
            const line = issue.title +','+ issue.number
              console.log(issue.title)
              console.log(issue.number)
              console.log(line)
              fs.write(path,line,'a')
            }
      - name: Check for file
        run: "ls $GITHUB_WORKSPACE/"
