name: Verify Commit Message
on: push
jobs:
  log-github-events-stuff:
    name: "Check Commit Message"
    runs-on: ubuntu-latest
    steps:
      - name: Logging event head commit
        run: |
          echo "${{toJSON(github.event.head_commit)}}"
      - name: Check commit message
        uses: actions/github-script@v4
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        with:
          script: |
            const commit_string = process.env.COMMIT_MESSAGE
            console.log(commit_string);
            const re = new RegExp("/\[#VISTAOR-[0-9]/g");
            console.log(re.test(commit_string));
            if (re.test(commit_string)) {
              console.log("Commit VALID");
            } else {
              console.log("Commit NOT VALID");
            }
        
