name: Verify Commit Message
on: push
jobs:
  log-github-events-stuff:
    name: "Log Head commit"
    runs-on: ubuntu-latest
    steps:
      - name: Logging event head commit
        run: |
          echo "${{toJSON(github.event.head_commit)}}"
      - name: Check commit message
        uses: actions/github-script@v4
        with:
          script: |
            const commit_string = ${{ github.event.head_commit.message }}
            console.log(commit_string);
        
