name: Verify Commit Message
on: push
jobs:
  log-github-events-stuff:
    name: "Log Head commit"
    runs-on: ubuntu-latest
    steps:
      - name: Logging event head commit
        run: |
          echo "${{toJSON(github.event.head_commit)}}"
      - name: Check commit message
        run: |
          s=${{ github.event.head_commit.message }}
          [[ $s =~ /\[#VISTAOR-[0-9]/g ]] && echo matched
