name: Verify Commit Message
on: push
jobs:
  log-github-events-stuff:
    name: "Log ALL THE THINGS"
    runs-on: ubuntu-latest
    steps:
      - name: Logging event head commit
        run: |
         echo "${{toJSON(github.event.head_commit.message)}}"
