name: Sprint Report
on:
  workflow_dispatch:

jobs:
  getissueswithsprintlabel:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workspace
        run: echo "$GITHUB_WORKSPACE"
      - uses: actions/github-script@v4
        with:
          script: |
            const query = `query($owner:String!, $name:String!, $label:String!) {
              repository(owner:$owner, name:$name){
                issues(first:100, labels: [$label]) {
                  nodes {
                    id
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              label: 'Sprin 1'
            }
            const result = await github.graphql(query, variables)
            console.log(result)
