name: Sprint Report
on:
  workflow_dispatch:

jobs:
  getissueswithsprintlabel:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workspace
        run: echo "$GITHUB_WORKSPACE"
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const query = `query($owner:String!, $name:String!, $label:String!) {
              organization(login: $owner) {
                repository(name:$name) {
                  issues(after: null, first: 100) {
                    nodes {
                      title
                      labels(first: 100, after: null) {
                        nodes {
                          name
                        }
                      }
                      assignees(first: 100, after: null) {
                        nodes {
                          login
                        }
                      }
                    }
                    pageInfo {
                      endCursor
                      hasNextPage
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              label: 'Sprint 1'
            }
            const result = await github.graphql(query, variables)
            let issues = result.repository.issues.nodes;
            for (const issue of issues) {console.log(issue)}
            
